<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
    <line>
      <![CDATA[running TC1]]>
    </line>
    <line>
      <![CDATA[running TC2]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="31" started-at="2021-03-31T08:50:41Z" finished-at="2021-03-31T08:50:41Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="31" started-at="2021-03-31T08:50:41Z" finished-at="2021-03-31T08:50:41Z">
      <class name="TestNG_Examples.sample4">
        <test-method status="PASS" signature="TC1()[pri:0, instance:TestNG_Examples.sample4@2f8f11]" name="TC1" duration-ms="16" started-at="2021-03-31T14:20:41Z" finished-at="2021-03-31T14:20:41Z">
          <reporter-output>
            <line>
              <![CDATA[running TC1]]>
            </line>
          </reporter-output>
        </test-method> <!-- TC1 -->
        <test-method status="PASS" signature="TC2()[pri:0, instance:TestNG_Examples.sample4@2f8f11]" name="TC2" duration-ms="0" started-at="2021-03-31T14:20:41Z" finished-at="2021-03-31T14:20:41Z">
          <reporter-output>
            <line>
              <![CDATA[running TC2]]>
            </line>
          </reporter-output>
        </test-method> <!-- TC2 -->
        <test-method status="FAIL" signature="TC3()[pri:0, instance:TestNG_Examples.sample4@2f8f11]" name="TC3" duration-ms="15" started-at="2021-03-31T14:20:41Z" finished-at="2021-03-31T14:20:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at TestNG_Examples.sample4.TC3(sample4.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC3 -->
      </class> <!-- TestNG_Examples.sample4 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
